sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: cbz
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: cbz
    user-ttl: 7200000
    user-token-name: authentication
    # 阿里云OSS配置
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: cbz-storage-space

    # 微信小程序配置
  wechat:
    appid: ${}
    secret: ${}